[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[context.production.environment]
  NODE_VERSION = "22.x"
  AWS_LAMBDA_JS_RUNTIME = "nodejs22.x"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
