[build]
  publish = "."  # Root directory since we're using static HTML
  command = ""   # No build command needed for static HTML

[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[context.production.environment]
  API_URL = "https://api.example.com"
