[build]
  publish = "." # Directly use root directory
  command = "" # No build command needed

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_VERSION = "18" # Still useful for any Node-based plugins
