[build]
  command = "npm run build:ssr"
  publish = "dist/epic-gardening/browser"
  functions = "dist/epic-gardening/server"

[[plugins]]
  package = "netlify-plugin-angular-universal"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  API_URL = "https://api.example.com"
  NODE_VERSION = "14.x"
