[build]
  publish = "."  # All HTML files are in root
  command = "echo 'Static site ready'" 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"

[context.production.environment]
  NODE_VERSION = "18"
