[build]
  command = "npm run build"
  publish = "dist"  # ACTUAL build output folder
  functions = "netlify/functions"  # Delete if not using functions

[context.production.environment]
  NODE_VERSION = "20.x"  # Enforced Node version
